'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {getBrowserSupabase} from '../../../lib/supabase-browser';

type Customer={id:string;name:string;phone:string|null};
type Vehicle={id:string;customer_id:string|null;registration:string;make:string|null;model:string|null;mot_due:string|null;service_due:string|null};
type Job={id:string;customer_name:string;phone:string|null;registration:string;vehicle:string;status:string};

type Reminder={kind:'MOT'|'Service'|'Ready';name:string;phone:string|null;registration:string;vehicle:string;date?:string;message:string};

function daysUntil(date:string){const today=new Date();today.setHours(0,0,0,0);const target=new Date(`${date}T00:00:00`);return Math.ceil((target.getTime()-today.getTime())/86400000)}
function cleanPhone(v:string|null){if(!v)return '';let p=v.replace(/\s+/g,'');if(p.startsWith('0'))p=`44${p.slice(1)}`;if(p.startsWith('+'))p=p.slice(1);return p}

export default function Reminders(){const supabase=useMemo(()=>getBrowserSupabase(),[]);const[ready,setReady]=useState(false);const[signedIn,setSignedIn]=useState(false);const[customers,setCustomers]=useState<Customer[]>([]);const[vehicles,setVehicles]=useState<Vehicle[]>([]);const[jobs,setJobs]=useState<Job[]>([]);const[message,setMessage]=useState('');const[windowDays,setWindowDays]=useState(45);
useEffect(()=>{if(!supabase){setReady(true);return}supabase.auth.getSession().then(({data})=>{setSignedIn(!!data.session);setReady(true);if(data.session)load()})},[supabase]);
async function load(){if(!supabase)return;const[c,v,j]=await Promise.all([supabase.from('customers').select('id,name,phone'),supabase.from('vehicles').select('id,customer_id,registration,make,model,mot_due,service_due'),supabase.from('job_cards').select('id,customer_name,phone,registration,vehicle,status').eq('status','ready')]);if(c.error||v.error||j.error){setMessage(c.error?.message||v.error?.message||j.error?.message||'Could not load reminders.');return}setCustomers((c.data||[]) as Customer[]);setVehicles((v.data||[]) as Vehicle[]);setJobs((j.data||[]) as Job[])}
const reminders=useMemo(()=>{const list:Reminder[]=[];for(const v of vehicles){const c=customers.find(x=>x.id===v.customer_id);const vehicle=[v.make,v.model].filter(Boolean).join(' ')||'your vehicle';if(v.mot_due){const d=daysUntil(v.mot_due);if(d>=0&&d<=windowDays)list.push({kind:'MOT',name:c?.name||'Customer',phone:c?.phone||null,registration:v.registration,vehicle,date:v.mot_due,message:`Hi ${c?.name||''}, just a reminder from L.A Motors Stroud that the MOT for ${v.registration} is due on ${v.mot_due}. If you would like us to help with the MOT when our MOT service is available, or prepare the car beforehand, please get in touch. Thanks, Liam - L.A Motors.`})}if(v.service_due){const d=daysUntil(v.service_due);if(d>=0&&d<=windowDays)list.push({kind:'Service',name:c?.name||'Customer',phone:c?.phone||null,registration:v.registration,vehicle,date:v.service_due,message:`Hi ${c?.name||''}, a quick reminder from L.A Motors Stroud that ${v.registration} is due a service around ${v.service_due}. If you would like to get it booked in, reply or call me and I can arrange a suitable date. Thanks, Liam - L.A Motors.`})}}for(const j of jobs)list.push({kind:'Ready',name:j.customer_name,phone:j.phone,registration:j.registration,vehicle:j.vehicle||'vehicle',message:`Hi ${j.customer_name}, your ${j.registration} is ready to collect from L.A Motors Stroud. Please get in touch if you need anything before collection. Thanks, Liam.`});return list},[vehicles,customers,jobs,windowDays]);
async function copy(text:string){await navigator.clipboard.writeText(text);setMessage('Message copied.')}
if(!ready)return <main className="shell section"><p className="muted">Loading…</p></main>;if(!supabase||!signedIn)return <main className="shell section"><div className="panel"><h1>Staff access required</h1><p className="muted">Sign in through Liam Dashboard first.</p><Link className="btn" href="/dashboard">Open Dashboard</Link></div></main>;
return <main className="shell section"><div className="dashboardTop"><div><div className="eyebrow">Customer Follow-Up</div><h1 className="sectionTitle">Reminders & Messages</h1><p className="muted">See upcoming MOT/service dates and ready-to-collect jobs, then copy or open a WhatsApp message without retyping customer details.</p></div><div className="actions"><Link className="btn ghost" href="/dashboard">Dashboard</Link><button className="btn ghost" onClick={load}>Refresh</button></div></div>{message&&<p className="formNotice">{message}</p>}<div className="panel"><div className="jobsHeader"><div><div className="eyebrow">Reminder Window</div><h2>{reminders.length} follow-ups</h2></div><select value={windowDays} onChange={e=>setWindowDays(Number(e.target.value))}><option value={30}>Next 30 days</option><option value={45}>Next 45 days</option><option value={60}>Next 60 days</option><option value={90}>Next 90 days</option></select></div><div className="reminderList">{reminders.length===0?<p className="muted">No reminders due in this window.</p>:reminders.map((r,i)=>{const wp=cleanPhone(r.phone);return <article className="reminderRow" key={`${r.kind}-${r.registration}-${i}`}><div><span className={`statusPill reminder-${r.kind.toLowerCase()}`}>{r.kind}</span><h3>{r.name} · {r.registration}</h3><p className="muted">{r.vehicle}{r.date?` · Due ${r.date}`:''}</p><p className="reminderMessage">{r.message}</p></div><div className="reminderActions"><button onClick={()=>copy(r.message)}>Copy Message</button>{r.phone&&<a href={`sms:${r.phone}?body=${encodeURIComponent(r.message)}`}>Text</a>}{wp&&<a target="_blank" rel="noreferrer" href={`https://wa.me/${wp}?text=${encodeURIComponent(r.message)}`}>WhatsApp</a>}{r.phone&&<a href={`tel:${r.phone}`}>Call</a>}</div></article>})}</div></div></main>}
