'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {getBrowserSupabase} from '../../../lib/supabase-browser';

type Job={id:string;customer_id:string|null;vehicle_id:string|null;customer_name:string;phone:string|null;registration:string;vehicle:string;job_type:string;description:string;technician_notes:string;status:string;scheduled_date:string|null;estimated_total:number|null;final_total:number|null};
const empty={customer_name:'',phone:'',registration:'',vehicle:'',job_type:'Service',description:'',technician_notes:'',scheduled_date:'',estimated_total:'',final_total:''};
const workflow=[['booked','Booked'],['in_progress','In Progress'],['waiting_parts','Waiting Parts'],['ready','Ready'],['completed','Completed']];
function niceDate(v:string|null){if(!v)return 'No date';const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})}
function cleanPhone(v:string|null){return (v||'').replace(/[^0-9+]/g,'')}
export default function Jobs(){
 const supabase=useMemo(()=>getBrowserSupabase(),[]);const[ready,setReady]=useState(false),[staff,setStaff]=useState(false),[jobs,setJobs]=useState<Job[]>([]),[form,setForm]=useState<any>(empty),[message,setMessage]=useState(''),[filter,setFilter]=useState('open'),[working,setWorking]=useState(''),[showNew,setShowNew]=useState(false);
 useEffect(()=>{(async()=>{if(!supabase){setReady(true);return}const{data:s}=await supabase.auth.getSession();if(!s.session){setReady(true);return}const{data:isStaff}=await supabase.rpc('is_staff');setStaff(!!isStaff);if(isStaff)await load();setReady(true)})()},[supabase]);
 async function load(){if(!supabase)return;const{data,error}=await supabase.from('job_cards').select('*').order('scheduled_date',{ascending:true}).order('created_at',{ascending:false});if(error)setMessage(error.message);else setJobs((data||[]) as Job[])}
 async function add(e:FormEvent){e.preventDefault();if(!supabase)return;setWorking('new');setMessage('');const payload={customer_name:form.customer_name.trim(),phone:form.phone.trim()||null,registration:form.registration.trim().toUpperCase(),vehicle:form.vehicle.trim(),job_type:form.job_type,description:form.description.trim(),technician_notes:'',scheduled_date:form.scheduled_date||null,estimated_total:form.estimated_total?Number(form.estimated_total):null,final_total:null,status:'booked'};const{error}=await supabase.from('job_cards').insert(payload);setWorking('');if(error)return setMessage(error.message);setForm(empty);setShowNew(false);setMessage('Job card created.');load()}
 async function patch(id:string,changes:Partial<Job>,note='Job updated.'){if(!supabase)return;setWorking(id);const{error}=await supabase.from('job_cards').update(changes).eq('id',id);setWorking('');if(error)return setMessage(error.message);setJobs(v=>v.map(j=>j.id===id?{...j,...changes}:j));setMessage(note)}
 async function createQuote(j:Job){if(!supabase)return;setWorking(`quote-${j.id}`);const existing=await supabase.from('quotes').select('id').eq('job_id',j.id).maybeSingle();if(existing.data){setMessage('A quote already exists for this job.');setWorking('');return}const amount=Number(j.estimated_total??j.final_total??0);const valid=new Date();valid.setDate(valid.getDate()+14);const{error}=await supabase.from('quotes').insert({job_id:j.id,customer_id:j.customer_id,vehicle_id:j.vehicle_id,customer_name:j.customer_name,phone:j.phone,registration:j.registration,vehicle:j.vehicle,description:j.description||j.job_type,amount,status:'draft',valid_until:valid.toISOString().slice(0,10)});setWorking('');setMessage(error?error.message:'Quote created. Open Finance to review it.')}
 async function createInvoice(j:Job){if(!supabase)return;setWorking(`invoice-${j.id}`);const existing=await supabase.from('invoices').select('id,invoice_number').eq('job_id',j.id).maybeSingle();if(existing.data){setMessage(`Invoice INV-${String(existing.data.invoice_number).padStart(5,'0')} already exists.`);setWorking('');return}const amount=Number(j.final_total??j.estimated_total??0);if(amount<=0){setMessage('Enter a final or estimated total before creating the invoice.');setWorking('');return}const due=new Date();due.setDate(due.getDate()+7);const{data,error}=await supabase.from('invoices').insert({job_id:j.id,customer_id:j.customer_id,vehicle_id:j.vehicle_id,customer_name:j.customer_name,phone:j.phone,registration:j.registration,vehicle:j.vehicle,description:j.description||j.job_type,amount,status:'unpaid',due_date:due.toISOString().slice(0,10)}).select('invoice_number').single();setWorking('');setMessage(error?error.message:`Invoice INV-${String(data.invoice_number).padStart(5,'0')} created.`)}
 const counts=Object.fromEntries(workflow.map(([key])=>[key,jobs.filter(j=>j.status===key).length]));const shown=jobs.filter(j=>filter==='all'||(filter==='open'?!['completed','cancelled'].includes(j.status):j.status===filter));
 if(!ready)return <main className="dashLoading">Loading workshop…</main>;if(!staff)return <main className="dashLogin"><div className="customerCard"><h1>Staff sign-in required</h1><p>Workshop job cards are private.</p><Link className="customerPrimary" href="/dashboard">Staff Login</Link></div></main>;
 return <main className="workshopJobs"><header className="workshopJobsTop"><div><Link href="/dashboard">← Today</Link><span className="premiumEyebrow">Workshop Control</span><h1>Job Cards</h1><p>Move each vehicle through the workshop from booking to collection.</p></div><div><Link href="/dashboard/schedule">Diary</Link><Link href="/dashboard/finance">Finance</Link><button onClick={()=>setShowNew(!showNew)}>＋ New Job</button></div></header>
 {message&&<div className="workshopNotice">{message}</div>}
 <section className="jobStatusBar"><button className={filter==='open'?'active':''} onClick={()=>setFilter('open')}><b>{jobs.filter(j=>!['completed','cancelled'].includes(j.status)).length}</b><span>Open</span></button>{workflow.map(([key,label])=><button key={key} className={filter===key?'active':''} onClick={()=>setFilter(key)}><b>{counts[key]||0}</b><span>{label}</span></button>)}<button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}><b>{jobs.length}</b><span>All</span></button></section>
 {showNew&&<form className="quickJobForm" onSubmit={add}><div className="quickJobHead"><div><span className="premiumEyebrow">New workshop job</span><h2>Create job card</h2></div><button type="button" onClick={()=>setShowNew(false)}>×</button></div><div className="formGrid"><label>Customer<input required value={form.customer_name} onChange={e=>setForm({...form,customer_name:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Registration<input required value={form.registration} onChange={e=>setForm({...form,registration:e.target.value.toUpperCase()})}/></label><label>Vehicle<input value={form.vehicle} onChange={e=>setForm({...form,vehicle:e.target.value})}/></label><label>Job Type<select value={form.job_type} onChange={e=>setForm({...form,job_type:e.target.value})}><option>Service</option><option>Diagnostics</option><option>Repair</option><option>Car Key</option><option>Air-Con</option><option>MOT</option><option>Vehicle Prep</option><option>Other</option></select></label><label>Date<input type="date" value={form.scheduled_date} onChange={e=>setForm({...form,scheduled_date:e.target.value})}/></label><label>Estimate £<input type="number" step="0.01" value={form.estimated_total} onChange={e=>setForm({...form,estimated_total:e.target.value})}/></label><label className="full">Work required<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><button className="workshopPrimary" disabled={working==='new'}>{working==='new'?'Creating…':'Create Job Card'}</button></form>}
 <section className="workshopQueueHead"><div><span className="premiumEyebrow">Workshop queue</span><h2>{shown.length} {filter==='open'?'open ':''}job{shown.length===1?'':'s'}</h2></div><button onClick={load}>↻ Refresh</button></section>
 <section className="workshopJobList">{shown.length===0?<div className="workshopEmpty">No jobs in this view.</div>:shown.map(j=>{const phone=cleanPhone(j.phone);return <article className={`workshopJob status-${j.status}`} key={j.id}><div className="workshopJobMain"><div className="workshopJobIdentity"><div className="workshopPlate">{j.registration||'NO REG'}</div><div><span className={`statusTag ${j.status}`}>{j.status.replaceAll('_',' ')}</span><h3>{j.job_type}</h3><p>{j.vehicle||'Vehicle details not supplied'}</p></div></div><div className="workshopCustomer"><small>CUSTOMER</small><b>{j.customer_name}</b><span>{j.phone||'No phone number'}</span><div>{phone&&<><a href={`tel:${phone}`}>Call</a><a href={`https://wa.me/${phone.replace(/^0/,'44')}?text=${encodeURIComponent(`Hi ${j.customer_name}, it's Liam from L.A Motors regarding ${j.registration}.`)}`}>WhatsApp</a></>}</div></div><div className="workshopDate"><small>BOOKED</small><b>{niceDate(j.scheduled_date)}</b><span>{j.description||'No job description'}</span></div></div>
 <div className="workshopFlow"><button disabled={working===j.id} className={j.status==='in_progress'?'current':''} onClick={()=>patch(j.id,{status:'in_progress'},'Job started.')}>Start Job</button><button disabled={working===j.id} className={j.status==='waiting_parts'?'current':''} onClick={()=>patch(j.id,{status:'waiting_parts'},'Marked as waiting for parts.')}>Waiting Parts</button><button disabled={working===j.id} className={j.status==='ready'?'current':''} onClick={()=>patch(j.id,{status:'ready'},'Vehicle marked ready for collection.')}>Ready</button><button disabled={working===j.id} className={j.status==='completed'?'current':''} onClick={()=>patch(j.id,{status:'completed'},'Job completed.')}>Complete</button></div>
 <div className="workshopJobEdit"><label>Technician / job notes<textarea defaultValue={j.technician_notes||''} placeholder="Work carried out, parts fitted, findings…" onBlur={e=>patch(j.id,{technician_notes:e.target.value},'Notes saved.')}/></label><div className="workshopMoney"><label>Estimate £<input type="number" step="0.01" defaultValue={j.estimated_total??''} onBlur={e=>patch(j.id,{estimated_total:e.target.value?Number(e.target.value):null},'Estimate saved.')}/></label><label>Final £<input type="number" step="0.01" defaultValue={j.final_total??''} onBlur={e=>patch(j.id,{final_total:e.target.value?Number(e.target.value):null},'Final total saved.')}/></label></div><div className="workshopFinance"><button disabled={working===`quote-${j.id}`} onClick={()=>createQuote(j)}>Quote</button><button disabled={working===`invoice-${j.id}`} onClick={()=>createInvoice(j)}>Invoice</button><Link href="/dashboard/finance">Open Finance</Link></div></div></article>})}</section>
 <nav className="ownerMobileNav"><Link href="/dashboard"><b>⌂</b><span>Today</span></Link><Link href="/dashboard/schedule"><b>▦</b><span>Diary</span></Link><Link href="/dashboard/jobs"><b>🔧</b><span>Jobs</span></Link><Link href="/dashboard/stock"><b>🚗</b><span>Stock</span></Link><Link href="/dashboard/finance"><b>£</b><span>Money</span></Link></nav>
 </main>
}
