'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {getBrowserSupabase} from '../../lib/supabase-browser';

type Booking={id:string;service:string;registration:string;vehicle:string;preferred_date:string;customer_name:string;phone:string;notes:string;status:string;created_at:string};
type Stock={id:string;status:string;featured:boolean};

export default function Dashboard(){
 const supabase=useMemo(()=>getBrowserSupabase(),[]);
 const [ready,setReady]=useState(false);const [signedIn,setSignedIn]=useState(false);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [authError,setAuthError]=useState('');const [bookings,setBookings]=useState<Booking[]>([]);const [stock,setStock]=useState<Stock[]>([]);const [loading,setLoading]=useState(false);const [dataError,setDataError]=useState('');
 useEffect(()=>{if(!supabase){setReady(true);return}supabase.auth.getSession().then(({data})=>{setSignedIn(!!data.session);setReady(true);if(data.session)loadData()});const {data:listener}=supabase.auth.onAuthStateChange((_event,session)=>{setSignedIn(!!session);if(session)loadData();else{setBookings([]);setStock([])}});return()=>listener.subscription.unsubscribe()},[supabase]);
 async function loadData(){if(!supabase)return;setLoading(true);setDataError('');const [b,s]=await Promise.all([supabase.from('bookings').select('*').order('created_at',{ascending:false}).limit(50),supabase.from('stock_vehicles').select('id,status,featured')]);if(b.error)setDataError(b.error.message);else setBookings((b.data||[]) as Booking[]);if(!s.error)setStock((s.data||[]) as Stock[]);setLoading(false)}
 async function signIn(e:FormEvent){e.preventDefault();if(!supabase){setAuthError('Supabase is not configured yet.');return}setAuthError('');setLoading(true);const {error}=await supabase.auth.signInWithPassword({email,password});setLoading(false);if(error)setAuthError('Sign in failed. Check the staff email and password.')}
 async function signOut(){if(supabase)await supabase.auth.signOut()}
 async function setStatus(id:string,status:string){if(!supabase)return;const {error}=await supabase.from('bookings').update({status}).eq('id',id);if(error){setDataError(error.message);return}setBookings(v=>v.map(b=>b.id===id?{...b,status}:b))}
 if(!ready)return <main className="shell section"><div className="panel"><p className="muted">Loading dashboard…</p></div></main>;
 if(!supabase)return <main className="shell section"><div className="sectionHead"><div className="eyebrow">Liam Operations</div><h1 className="sectionTitle">Dashboard setup required</h1><p className="muted">Add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY to the V3 environment to switch on the live staff dashboard.</p></div></main>;
 if(!signedIn)return <main className="shell section"><div className="sectionHead"><div className="eyebrow">Staff Only</div><h1 className="sectionTitle">Liam Dashboard</h1><p className="muted">Sign in with the L.A Motors staff account to view customer bookings and vehicle stock.</p></div><form className="formCard card" onSubmit={signIn}><div className="formGrid"><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label></div>{authError&&<p className="formError">{authError}</p>}<div className="actions"><button className="btn" disabled={loading}>{loading?'Signing in…':'Sign In'}</button></div></form></main>;
 const pending=bookings.filter(b=>b.status==='pending').length;const confirmed=bookings.filter(b=>b.status==='confirmed').length;const liveStock=stock.filter(s=>s.status==='available').length;const reserved=stock.filter(s=>s.status==='reserved').length;
 return <main className="shell section"><div className="dashboardTop"><div><div className="eyebrow">Live Operations</div><h1 className="sectionTitle">Workshop Dashboard</h1><p className="muted">Shared bookings and stock from Supabase.</p></div><div className="actions"><button className="btn ghost" onClick={loadData} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button><button className="btn ghost" onClick={signOut}>Sign Out</button></div></div>{dataError&&<p className="formError">{dataError}</p>}<div className="dashboardGrid"><div className="stat card"><small>Pending Bookings</small><strong>{pending}</strong></div><div className="stat card"><small>Confirmed</small><strong>{confirmed}</strong></div><div className="stat card"><small>Cars For Sale</small><strong>{liveStock}</strong></div><div className="stat card"><small>Reserved Stock</small><strong>{reserved}</strong></div></div><section className="panel" style={{marginTop:20}}><div className="eyebrow">Latest Requests</div><h2>Customer Bookings</h2>{bookings.length===0?<p className="muted">No booking requests yet.</p>:<div className="bookingAdminList">{bookings.map(b=><article className="bookingAdminRow" key={b.id}><div><span className={`statusPill status-${b.status}`}>{b.status.replace('_',' ')}</span><h3>{b.service}</h3><p className="muted">{b.preferred_date} · {b.vehicle||'Vehicle not supplied'} · {b.registration}</p><p><b>{b.customer_name}</b> · <a href={`tel:${b.phone}`}>{b.phone}</a></p>{b.notes&&<p className="muted">{b.notes}</p>}</div><div className="bookingAdminActions"><button onClick={()=>setStatus(b.id,'confirmed')}>Confirm</button><button onClick={()=>setStatus(b.id,'in_progress')}>Start</button><button onClick={()=>setStatus(b.id,'completed')}>Complete</button><button onClick={()=>setStatus(b.id,'cancelled')}>Cancel</button></div></article>)}</div>}</section><div className="split" style={{marginTop:20}}><section className="panel"><div className="eyebrow">Vehicle Sales</div><h2>Stock</h2><div className="heroStats"><div className="heroStat"><b>{liveStock}</b><small>Available</small></div><div className="heroStat"><b>{reserved}</b><small>Reserved</small></div><div className="heroStat"><b>{stock.filter(s=>s.featured).length}</b><small>Featured</small></div></div><div className="actions"><Link className="btn" href="/dashboard/stock">Manage Stock</Link><Link className="btn ghost" href="/cars">Open Showroom</Link></div></section><section className="panel"><div className="eyebrow">Workshop Control</div><h2>Next tools</h2><p className="muted">Customers, job cards, quotes and reminders can now build on the same protected Supabase foundation.</p></section></div></main>
}
