'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {getBrowserSupabase} from '../../lib/supabase-browser';

type Booking={id:string;service:string;registration:string;vehicle:string;preferred_date:string;customer_name:string;phone:string;notes:string;status:string;created_at:string};
type Stock={id:string;status:string;featured:boolean};
type Job={id:string;customer_name:string;registration:string;vehicle:string;job_type:string;scheduled_date:string;status:string;created_at:string};
type Invoice={id:string;status:string;total:number|null};
function day(v?:string){if(!v)return 'Date TBC';const d=new Date(v+'T12:00:00');return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})}
function todayKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
export default function Dashboard(){
 const supabase=useMemo(()=>getBrowserSupabase(),[]);const[ready,setReady]=useState(false),[signedIn,setSignedIn]=useState(false),[isStaff,setIsStaff]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authError,setAuthError]=useState(''),[bookings,setBookings]=useState<Booking[]>([]),[stock,setStock]=useState<Stock[]>([]),[jobs,setJobs]=useState<Job[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[customers,setCustomers]=useState(0),[loading,setLoading]=useState(false),[dataError,setDataError]=useState(''),[workingId,setWorkingId]=useState<string|null>(null),[notice,setNotice]=useState('');
 useEffect(()=>{if(!supabase){setReady(true);return}supabase.auth.getSession().then(({data})=>checkSession(data.session));const{data:l}=supabase.auth.onAuthStateChange((_e,s)=>checkSession(s));return()=>l.subscription.unsubscribe()},[supabase]);
 async function checkSession(session:any){if(!supabase){setReady(true);return}if(!session){setSignedIn(false);setIsStaff(false);setReady(true);return}setSignedIn(true);const{data,error}=await supabase.rpc('is_staff');if(error){setAuthError('Staff security setup is not complete yet.');setReady(true);return}setIsStaff(!!data);if(data)await loadData();setReady(true)}
 async function loadData(){if(!supabase)return;setLoading(true);setDataError('');const[b,s,j,i,c]=await Promise.all([supabase.from('bookings').select('*').order('preferred_date',{ascending:true}).limit(100),supabase.from('stock_vehicles').select('id,status,featured'),supabase.from('job_cards').select('id,customer_name,registration,vehicle,job_type,scheduled_date,status,created_at').order('scheduled_date',{ascending:true}).limit(100),supabase.from('invoices').select('id,status,total').limit(100),supabase.from('customers').select('id',{count:'exact',head:true})]);const errs=[b.error,s.error,j.error,i.error,c.error].filter(Boolean);if(errs.length)setDataError((errs[0] as any).message);setBookings((b.data||[]) as Booking[]);setStock((s.data||[]) as Stock[]);setJobs((j.data||[]) as Job[]);setInvoices((i.data||[]) as Invoice[]);setCustomers(c.count||0);setLoading(false)}
 async function signIn(e:FormEvent){e.preventDefault();if(!supabase)return;setLoading(true);setAuthError('');const{error}=await supabase.auth.signInWithPassword({email,password});setLoading(false);if(error)setAuthError('Sign in failed. Check the staff email and password.')}
 async function signOut(){if(supabase)await supabase.auth.signOut()}
 async function createJob(b:Booking){if(!supabase)return;setWorkingId(b.id);setNotice('');try{const existing=await supabase.from('job_cards').select('id').eq('booking_id',b.id).maybeSingle();if(existing.data){setNotice('This booking already has a job card.');return}let customerId:string|null=null;const ec=await supabase.from('customers').select('id').eq('phone',b.phone).limit(1).maybeSingle();if(ec.data?.id)customerId=ec.data.id;else{const c=await supabase.from('customers').insert({name:b.customer_name,phone:b.phone}).select('id').single();if(c.error)throw c.error;customerId=c.data.id}const reg=b.registration.trim().toUpperCase();let vehicleId:string|null=null;const ev=await supabase.from('vehicles').select('id').eq('registration',reg).limit(1).maybeSingle();if(ev.data?.id)vehicleId=ev.data.id;else{const p=b.vehicle.trim().split(/\s+/);const v=await supabase.from('vehicles').insert({customer_id:customerId,registration:reg,make:p[0]||null,model:p.slice(1).join(' ')||null}).select('id').single();if(v.error)throw v.error;vehicleId=v.data.id}const j=await supabase.from('job_cards').insert({customer_id:customerId,vehicle_id:vehicleId,booking_id:b.id,customer_name:b.customer_name,phone:b.phone,registration:reg,vehicle:b.vehicle||'',job_type:b.service,description:b.notes||'',scheduled_date:b.preferred_date,status:'booked'});if(j.error)throw j.error;await supabase.from('bookings').update({status:'confirmed'}).eq('id',b.id);setNotice('Job created and booking confirmed.');await loadData()}catch(e:any){setDataError(e?.message||'Could not create job.')}finally{setWorkingId(null)}}
 if(!ready)return <main className="dashLoading">Loading dashboard…</main>;if(!supabase)return <main className="dashSetup"><h1>Dashboard setup required</h1></main>;
 if(!signedIn)return <main className="dashLogin"><form onSubmit={signIn}><div className="dashLogo">L.A</div><h1>Liam's Garage Dashboard</h1><p>Private staff sign in</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{authError&&<p className="formError">{authError}</p>}<button className="btn blue" disabled={loading}>{loading?'Signing in…':'Sign In'}</button></form></main>;
 if(!isStaff)return <main className="dashLogin"><div className="customerCard"><h1>Staff access only</h1><Link className="customerPrimary" href="/my-garage">Open My Garage</Link><button onClick={signOut}>Sign Out</button></div></main>;
 const today=todayKey(),todaysJobs=jobs.filter(j=>j.scheduled_date===today&&j.status!=='completed'&&j.status!=='cancelled'),newBookings=bookings.filter(b=>b.status==='pending'),activeJobs=jobs.filter(j=>['booked','in_progress','waiting_parts','ready'].includes(j.status)),readyJobs=jobs.filter(j=>j.status==='ready'),available=stock.filter(s=>s.status==='available').length,reserved=stock.filter(s=>s.status==='reserved').length,outstanding=invoices.filter(i=>!['paid','cancelled'].includes(i.status)).reduce((n,i)=>n+Number(i.total||0),0);const diary=jobs.filter(j=>j.status!=='completed'&&j.status!=='cancelled').slice(0,7);
 return <main className="garageApp"><aside className="garageSidebar"><div className="garageBrand"><span className="dashLogo">L.A</span><div><b>L.A MOTORS</b><small>LIAM'S CONTROL</small></div></div><nav><span className="active">⌂ Today</span><Link href="/dashboard/schedule">▦ Schedule</Link><Link href="/dashboard/jobs">🔧 Job Cards</Link><Link href="/dashboard/customers">♙ Customers</Link><Link href="/dashboard/stock">🚗 Vehicle Stock</Link><Link href="/dashboard/finance">£ Quotes & Invoices</Link><Link href="/dashboard/reminders">◌ Reminders</Link></nav><button onClick={signOut}>⇥ Sign Out</button></aside><section className="garageMain"><header className="garageTop ownerControlTop"><div><span className="premiumEyebrow">L.A Motors Stroud Ltd</span><h1>Today at the garage</h1><p>{new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'})}</p></div><div><button onClick={loadData}>{loading?'Refreshing…':'↻ Refresh'}</button><span className="ownerChip">Liam <b>L</b></span></div></header>
 <div className="ownerActionDock"><Link className="ownerActionPrimary" href="/booking"><b>＋</b><span>New Booking<small>Book a customer in</small></span></Link><Link href="/dashboard/jobs"><b>🔧</b><span>New / Open Job<small>Workshop job cards</small></span></Link><Link href="/dashboard/customers"><b>♙</b><span>Customers<small>{customers} on file</small></span></Link><Link href="/dashboard/stock"><b>🚗</b><span>Add Vehicle<small>Manage showroom</small></span></Link></div>
 {dataError&&<p className="formError dashMessage">{dataError}</p>}{notice&&<p className="formNotice dashMessage">{notice}</p>}
 <div className="ownerPulse"><Link href="/dashboard/schedule"><small>TODAY'S WORK</small><strong>{todaysJobs.length}</strong><span>jobs scheduled</span></Link><div className={newBookings.length?'needsAttention':''}><small>NEW REQUESTS</small><strong>{newBookings.length}</strong><span>need reviewing</span></div><Link href="/dashboard/jobs"><small>ACTIVE JOBS</small><strong>{activeJobs.length}</strong><span>{readyJobs.length} ready to collect</span></Link><Link href="/dashboard/stock"><small>VEHICLE SALES</small><strong>{available}</strong><span>{reserved} reserved</span></Link><Link href="/dashboard/finance"><small>OUTSTANDING</small><strong>£{outstanding.toLocaleString()}</strong><span>invoice value</span></Link></div>
 <div className="ownerWorkGrid"><section className="ownerTodayPanel"><div className="panelHead"><div><span className="premiumEyebrow">Workshop</span><h2>Today's jobs</h2></div><Link href="/dashboard/schedule">Full diary →</Link></div>{todaysJobs.length===0?<div className="ownerEmpty"><b>No jobs showing for today</b><span>Use Schedule to add or review upcoming work.</span><Link href="/dashboard/schedule">Open schedule</Link></div>:todaysJobs.map(j=><article className="ownerJobRow" key={j.id}><div className="ownerReg">{j.registration||'NO REG'}</div><div><b>{j.customer_name}</b><span>{j.job_type} · {j.vehicle||j.registration}</span></div><em className={`statusTag ${j.status}`}>{j.status.replaceAll('_',' ')}</em><Link href="/dashboard/jobs">Open</Link></article>)}</section>
 <section className="ownerRequests"><div className="panelHead"><div><span className="premiumEyebrow">Incoming</span><h2>Booking requests</h2></div><span>{newBookings.length} new</span></div>{newBookings.length===0?<div className="ownerEmpty"><b>All caught up</b><span>No new customer requests waiting.</span></div>:newBookings.slice(0,5).map(b=><article className="ownerRequestRow" key={b.id}><div><b>{b.customer_name}</b><span>{b.service} · {b.registration||b.vehicle}</span><small>{day(b.preferred_date)} · {b.phone}</small></div><button disabled={workingId===b.id} onClick={()=>createJob(b)}>{workingId===b.id?'Creating…':'Create Job'}</button></article>)}</section>
 <section className="ownerDiary"><div className="panelHead"><div><span className="premiumEyebrow">Next up</span><h2>Upcoming diary</h2></div><Link href="/dashboard/schedule">Schedule →</Link></div>{diary.length===0?<div className="ownerEmpty"><span>No upcoming jobs.</span></div>:diary.map(j=><article key={j.id}><time>{day(j.scheduled_date)}</time><div><b>{j.registration||j.vehicle}</b><span>{j.job_type} · {j.customer_name}</span></div><em className={`statusTag ${j.status}`}>{j.status.replaceAll('_',' ')}</em></article>)}</section></div>
 <nav className="ownerMobileNav"><Link href="/dashboard"><b>⌂</b><span>Today</span></Link><Link href="/dashboard/schedule"><b>▦</b><span>Diary</span></Link><Link href="/dashboard/jobs"><b>🔧</b><span>Jobs</span></Link><Link href="/dashboard/stock"><b>🚗</b><span>Stock</span></Link><Link href="/dashboard/finance"><b>£</b><span>Money</span></Link></nav></section></main>;
}
