import Link from 'next/link';
import {getSupabase} from '../../../lib/supabase';
import {demoStockBySlug} from '../../../lib/demo-stock';
import VehicleGallery from './VehicleGallery';

export default async function Vehicle({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const supabase=getSupabase();let car:any=demoStockBySlug(slug)||null;let live=false;
 if(car)car={...car,mot:null,service_history:null,colour:car.make==='SEAT'?'Red':car.make==='Renault'?'Black':null,description:'Current L.A Motors advertised stock used to demonstrate the showroom. Contact Liam for the full specification, history and viewing availability.'};
 if(supabase){const {data,error}=await supabase.from('stock_vehicles').select('*').eq('slug',slug).in('status',['available','reserved']).maybeSingle();if(!error&&data){car=data;live=true}}
 if(!car)return <main className="shell section"><Link className="textLink" href="/cars">← Back to showroom</Link><div className="panel"><h1>Vehicle not found</h1><p className="muted">This advert may have been removed or sold.</p><Link className="btn" href="/cars">View current stock</Link></div></main>;
 const name=`${car.make} ${car.model}${car.derivative?` ${car.derivative}`:''}`;
 return <main className="vehicleAdvertPage">
  <section className="shell vehicleTop"><Link className="textLink" href="/cars">← Back to showroom</Link><div className="vehicleTitle"><div><div className="eyebrow">{car.status==='reserved'?'Reserved Vehicle':car.source||'L.A Motors Stock'}</div><h1 className="sectionTitle">{name}</h1><p className="muted">{car.year||'Year on request'} · {car.mileage?`${Number(car.mileage).toLocaleString()} miles`:'Mileage on request'} · {car.fuel||'Fuel on request'}</p></div><div className="vehiclePrice"><small>Advertised Price</small><strong>{car.price?`£${Number(car.price).toLocaleString()}`:'POA'}</strong></div></div></section>
  <section className="shell vehicleLayout"><div className="vehicleGalleryWrap"><VehicleGallery images={car.image_urls||[]}/>{car.demoPhoto&&<div className="vehiclePhotoNote">Demo showroom image only — Liam can replace this with the real vehicle photos from Stock Management.</div>}</div><aside className="vehicleSidebar"><div className="eyebrow">Vehicle Overview</div><div className="specTable"><div><span>Year</span><b>{car.year||'On request'}</b></div><div><span>Mileage</span><b>{car.mileage?Number(car.mileage).toLocaleString():'On request'}</b></div><div><span>Fuel</span><b>{car.fuel||'On request'}</b></div><div><span>Gearbox</span><b>{car.gearbox||'On request'}</b></div><div><span>Colour</span><b>{car.colour||'On request'}</b></div><div><span>Registration</span><b>{car.registration||'Ask Liam'}</b></div></div><div className="salesActions"><Link className="btn" href="/booking?service=Vehicle%20Viewing">Book a Viewing</Link><a className="btn ghost" href="tel:07484770941">Call Liam</a><Link className="btn ghost" href="/booking?service=Vehicle%20Viewing">Enquire / Part Exchange</Link></div>{!live&&<p className="finePrint">Demo advert. Once imported into Stock Management Liam controls whether this vehicle is available, reserved, sold or hidden.</p>}</aside></section>
  <section className="shell section"><div className="split"><div className="panel"><div className="eyebrow">Vehicle Details</div><h2>Everything customers need in one place.</h2><p className="muted">{car.description}</p><div className="checkList"><div>✓ Current advertised price shown</div><div>✓ Direct viewing request</div><div>✓ Call Liam from the advert</div><div>✓ Part-exchange enquiry route</div></div></div><div className="panel"><div className="eyebrow">Interested?</div><h2>Arrange a closer look.</h2><p className="muted">Send a viewing request and Liam can confirm a suitable time directly with the customer.</p><div className="actions"><Link className="btn" href="/booking?service=Vehicle%20Viewing">Request Viewing</Link><a className="btn ghost" href="tel:07484770941">07484 770941</a></div></div></div></section>
 </main>
}
