import Link from 'next/link';
import {getSupabase} from '../../lib/supabase';

const demo=[
 {slug:'ford-focus-st-line',make:'Ford',model:'Focus',derivative:'ST-Line',price:11995,mileage:42000,fuel:'Diesel',gearbox:'Automatic',featured:true,status:'available',image_urls:[]},
 {slug:'vauxhall-corsa-sri',make:'Vauxhall',model:'Corsa',derivative:'SRi',price:7995,mileage:51000,fuel:'Petrol',gearbox:'Manual',featured:false,status:'available',image_urls:[]},
 {slug:'bmw-320d-m-sport',make:'BMW',model:'320d',derivative:'M Sport',price:10995,mileage:68000,fuel:'Diesel',gearbox:'Automatic',featured:false,status:'available',image_urls:[]}
];
export default async function Cars(){const supabase=getSupabase();let cars:any[]=demo;let live=false;if(supabase){const {data,error}=await supabase.from('stock_vehicles').select('slug,make,model,derivative,price,mileage,fuel,gearbox,featured,status,image_urls').in('status',['available','reserved']).order('featured',{ascending:false}).order('created_at',{ascending:false});if(!error&&data){cars=data;live=true}}
 return <main className="shell section"><div className="sectionHead"><div className="eyebrow">L.A Motors Vehicle Sales</div><h1 className="sectionTitle">Cars for sale</h1><p className="muted">Clear pricing, useful specifications and a straightforward route to book a viewing or speak to Liam.</p>{!live&&<p className="finePrint">Demo stock is shown until Supabase is configured and live vehicles are added.</p>}</div><div className="grid3">{cars.length===0?<div className="panel"><h2>No live stock right now</h2><p className="muted">Call Liam with your budget and requirements.</p></div>:cars.map(c=><article className="card" key={c.slug}><div className="stockImage" style={{height:210,borderRadius:16,marginBottom:18}}>{c.image_urls?.[0]?<img src={c.image_urls[0]} alt={`${c.make} ${c.model}`} className="stockPhoto"/>:<div className="carSilhouette"/>}</div><div className="eyebrow">{c.status==='reserved'?'Reserved':c.featured?'Featured Stock':'Available Now'}</div><h3>{c.make} {c.model} {c.derivative||''}</h3><div className="specs"><span className="pill">{c.mileage?`${Number(c.mileage).toLocaleString()} miles`:'Mileage TBC'}</span><span className="pill">{c.fuel||'Fuel TBC'}</span><span className="pill">{c.gearbox||'Gearbox TBC'}</span></div><div className="priceBig">{c.price?`£${Number(c.price).toLocaleString()}`:'POA'}</div><div className="actions"><Link className="btn" href={`/cars/${c.slug}`}>View Vehicle</Link><a className="btn ghost" href="tel:07484770941">Call Liam</a></div></article>)}</div><div className="panel" style={{marginTop:24,textAlign:'center'}}><div className="eyebrow">Looking for something specific?</div><h2>Tell Liam what you need.</h2><p className="muted">If the right car is not listed, call with your budget and requirements.</p><div className="actions" style={{justifyContent:'center'}}><a className="btn" href="tel:07484770941">Call 07484 770941</a></div></div></main>}
