import Link from 'next/link';
import {getSupabase} from '../lib/supabase';

export default async function Home(){
 const supabase=getSupabase();let cars:any[]=[];
 if(supabase){const{data}=await supabase.from('stock_vehicles').select('slug,make,model,derivative,year,price,mileage,fuel,gearbox,status,image_urls').in('status',['available','reserved']).order('featured',{ascending:false}).order('created_at',{ascending:false}).limit(4);cars=data||[]}
 return <main>
<section className="premiumHero"><div className="shell premiumHeroInner"><div><span className="premiumEyebrow">L.A Motors Stroud Ltd · Automotive Specialists</span><h1><span>Workshop expertise.</span>Quality used cars.</h1><p>Car keys, air-conditioning, diagnostics, repairs, servicing and carefully selected used vehicles — all from one local Stroud garage.</p><div className="premiumActions"><Link className="premiumBtn primary" href="/services">Choose a Service</Link><Link className="premiumBtn" href="/cars">View Used Cars</Link><a className="premiumBtn" href="tel:07484770941">Call 07484 770941</a></div><div className="premiumTrust"><span>Fully insured</span><span>Professional equipment</span><span>Experienced technicians</span><span>Competitive prices</span></div></div><div className="heroServiceBoard"><div className="heroServiceHead">Book popular services</div><Link className="heroServiceRow" href="/booking?service=Car%20Keys"><span>Car keys</span><b>From £69</b></Link><Link className="heroServiceRow" href="/booking?service=Air-Con"><span>Air-con re-gas</span><b>From £50</b></Link><Link className="heroServiceRow" href="/booking?service=Diagnostics"><span>Diagnostics</span><b>Book now</b></Link><Link className="heroServiceRow" href="/booking?service=Servicing%20%26%20Repairs"><span>Servicing & repairs</span><b>Book now</b></Link><div className="heroServiceFoot">Tap a service to start booking →</div></div></div></section>

<section className="premiumSection"><div className="shell"><div className="premiumSectionHead"><div><span className="premiumEyebrow">Current showroom</span><h2>{cars.length?'Used cars available now':'Looking for your next car?'}</h2></div><Link href="/cars">View full showroom →</Link></div>{cars.length?<div className="premiumCars">{cars.map(c=><article className="premiumCard vehicleCard" key={c.slug}><Link href={`/cars/${c.slug}`} className="vehiclePhoto">{c.status==='reserved'&&<span className="stockTag">Reserved</span>}{c.image_urls?.[0]?<img src={c.image_urls[0]} alt={`${c.make} ${c.model}`} className="stockPhoto"/>:<div className="carSilhouette"/>}</Link><div className="vehicleBody"><h3>{c.make} {c.model}</h3><p>{c.derivative||'Details available on request'}</p><div className="vehicleSpecs"><span>{c.year||'Year TBC'}</span><span>{c.fuel||'Fuel TBC'}</span><span>{c.mileage?`${Number(c.mileage).toLocaleString()} miles`:'Mileage TBC'}</span></div><div className="vehicleFoot"><strong>{c.price?`£${Number(c.price).toLocaleString()}`:'POA'}</strong><Link href={`/cars/${c.slug}`} className="miniBtn">View Details</Link></div></div></article>)}</div>:<div className="homeStockEmpty"><div><span className="premiumEyebrow">Vehicle sourcing</span><h3>No live stock listed right now.</h3><p>Tell Liam what you are looking for and your budget, or check back as new cars are added.</p></div><div className="premiumActions"><Link className="premiumBtn primary" href="/cars">Open Showroom</Link><a className="premiumBtn" href="tel:07484770941">Speak to Liam</a></div></div>}</div></section>

<section className="workshopPosterSection"><div className="shell workshopPosterGrid"><article className="posterPanel"><span className="premiumEyebrow">Car keys</span><h2>Cut & programmed <span>while you wait.</span></h2><p>Spare keys, lost keys, remote keys, blade keys, immobiliser programming and key coding for all makes and models.</p><div className="posterPrice"><div><small>Blade keys from</small><b>£69</b></div><div><small>Remote keys from</small><b>£99</b></div></div><div className="posterChecks"><span>All makes & models</span><span>Immobiliser programming</span><span>Key coding</span><span>Fast local service</span></div><Link className="posterCta" href="/booking?service=Car%20Keys">BOOK CAR KEYS →</Link></article><article className="posterPanel"><span className="premiumEyebrow">Air-con re-gas</span><h2>Keep your <span>cool.</span></h2><p>Professional air-conditioning re-gas using specialist equipment, with leak checks available.</p><div className="posterPrice"><div><small>R134a from</small><b>£50</b></div><div><small>R1234yf from</small><b>£80</b></div></div><div className="posterChecks"><span>Colder air</span><span>Removes moisture</span><span>Protects compressor</span><span>Improves efficiency</span></div><Link className="posterCta" href="/booking?service=Air-Con">BOOK AIR-CON →</Link></article></div></section>

<section className="premiumSell"><div className="shell premiumSellInner"><div><span className="premiumEyebrow">Need something else?</span><h2>Diagnostics, servicing & repairs.</h2><p>Choose the job you need and send the vehicle details directly into the workshop diary.</p></div><div className="premiumActions"><Link className="premiumBtn primary" href="/services">View All Services</Link><Link className="premiumBtn" href="/booking">Book Online</Link></div></div></section>
</main>}
