import Link from 'next/link';

const demoCars=[
 {make:'BMW',model:'3 Series',detail:'320d M Sport Saloon',year:'2018 (68)',fuel:'Diesel',miles:'72,450 miles',price:'£14,995',tone:'carBlue'},
 {make:'Audi',model:'A3',detail:'2.0 TDI S Line Sportback',year:'2017 (67)',fuel:'Diesel',miles:'68,320 miles',price:'£12,995',tone:'carSilver'},
 {make:'Volkswagen',model:'Golf',detail:'1.5 TSI EVO SE',year:'2019 (19)',fuel:'Petrol',miles:'55,210 miles',price:'£11,495',tone:'carGrey'},
 {make:'Ford',model:'Fiesta',detail:'1.0 EcoBoost ST-Line',year:'2018 (18)',fuel:'Petrol',miles:'41,850 miles',price:'£8,495',tone:'carRed'}
];

export default function Home(){return <main>
<section className="showroomHero"><div className="shell showroomHeroGrid"><div className="showroomIntro"><span className="kicker">L.A Motors Stroud Ltd</span><h1>Quality used cars</h1><h2>Hand picked. Fair prices.</h2><p>Browse current stock, arrange a viewing, book workshop work or speak directly with Liam.</p><div className="actions"><Link className="btn blue" href="/cars">View All Cars →</Link><Link className="btn showroomOutline" href="/booking">Book a Service</Link></div><div className="showroomTrust"><span><i>✓</i><b>Inspected</b><small>Workshop checked</small></span><span><i>✓</i><b>Local</b><small>Stroud based</small></span><span><i>✓</i><b>Direct</b><small>Deal with Liam</small></span></div></div><div className="heroStockArea"><div className="stockTopline"><div><span className="kicker">Latest stock</span><strong>Available now</strong></div><Link href="/cars">View showroom →</Link></div><div className="heroCarGrid">{demoCars.map(c=><article className="vehicleCard" key={c.make+c.model}><div className={`vehiclePhoto ${c.tone}`}><span className="stockTag">Available</span><div className="carShape"><i/><i/></div></div><div className="vehicleBody"><h3>{c.make} {c.model}</h3><p>{c.detail}</p><div className="vehicleSpecs"><span>{c.year}</span><span>{c.fuel}</span><span>{c.miles}</span></div><div className="vehicleFoot"><strong>{c.price}</strong><Link href="/cars" className="miniBtn">View Details</Link></div></div></article>)}</div></div></div></section>

<section className="brandRibbon"><div className="shell brandRibbonGrid"><div><span>01</span><b>Car Keys</b><small>Cut & programmed</small></div><div><span>02</span><b>Air Conditioning</b><small>R134a & R1234yf</small></div><div><span>03</span><b>Diagnostics</b><small>Fault finding</small></div><div><span>04</span><b>Servicing & Repairs</b><small>Workshop care</small></div><div><span>05</span><b>Vehicle Sales</b><small>Buy & sell</small></div></div></section>

<section className="shell workshopFeature"><div className="workshopCopy"><span className="kicker">Automotive specialists</span><h2>Workshop knowledge.<br/>Straightforward service.</h2><p>Car keys, air-conditioning, diagnostics, repairs and servicing with clear pricing and direct local support.</p><div className="actions"><Link className="btn dark" href="/services">Explore Services</Link><Link className="btn outline" href="/booking">Book Online</Link></div></div><div className="priceBoard"><div className="priceBoardHead">Popular services</div><div className="priceLine"><span>Blade keys</span><b>from £69</b></div><div className="priceLine"><span>Remote keys</span><b>from £99</b></div><div className="priceLine"><span>R134a air-con</span><b>from £50</b></div><div className="priceLine"><span>R1234yf air-con</span><b>from £80</b></div><Link href="/booking">Book a service →</Link></div></section>

<section className="sellBand"><div className="shell sellBandInner"><div><span className="kicker">Vehicle sales</span><h2>Looking to sell your car?</h2><p>Speak to Liam about your vehicle and get a straightforward local conversation about selling or part exchange.</p></div><div className="actions"><a className="btn blue" href="tel:07484770941">Call Liam</a><Link className="btn outlineDark" href="/cars">Browse Showroom</Link></div></div></section>

<section className="shell opsTeaser"><div><span className="kicker">For Liam</span><h2>One garage dashboard.</h2><p>Bookings, jobs, customers, stock, quotes, invoices and reminders in one clean control centre.</p></div><Link className="btn dark" href="/dashboard">Open Dashboard →</Link></section>
</main>}
