'use client';
import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import './booking.css';

const steps=['Service','Vehicle','Date','Contact','Review'];
const services=[
 {code:'KEY',name:'Car Keys',hint:'Replacement, spare or lost key'},
 {code:'A/C',name:'Air-Con',hint:'Air-conditioning re-gas'},
 {code:'DIA',name:'Diagnostics',hint:'Warning lights or fault finding'},
 {code:'SRV',name:'Servicing & Repairs',hint:'Maintenance or mechanical repair'},
 {code:'MOT',name:'MOT Interest',hint:'Register for future MOT bookings'},
 {code:'CAR',name:'Vehicle Viewing',hint:'Book a viewing for a used car'}
];

export default function Booking(){
 const params=useSearchParams();
 const [step,setStep]=useState(0),[submitted,setSubmitted]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({service:'',reg:'',vehicle:'',date:'',name:'',phone:'',notes:''});
 useEffect(()=>{const requested=params.get('service');if(requested&&services.some(s=>s.name===requested)){setForm(f=>({...f,service:requested}));setStep(1)}},[params]);
 const update=(k:string,v:string)=>setForm({...form,[k]:v});
 const canContinue=useMemo(()=>{if(step===1)return form.reg.trim().length>=5;if(step===2)return !!form.date;if(step===3)return form.name.trim().length>1&&form.phone.trim().length>6;return true},[step,form]);
 const selected=services.find(s=>s.name===form.service);
 async function submit(){setSaving(true);setError('');try{const response=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({service:form.service,registration:form.reg,vehicle:form.vehicle,preferred_date:form.date,customer_name:form.name,phone:form.phone,notes:form.notes})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not save request.');setSubmitted(true)}catch(err){setError(err instanceof Error?err.message:'Could not save request.')}finally{setSaving(false)}}
 if(submitted)return <main className="bookingPage"><div className="shell bookingSuccessWrap"><div className="bookingSuccess"><span className="bookingKicker">REQUEST RECEIVED</span><div className="bookingSuccessMark">✓</div><h1>We’ve got your booking request.</h1><p>L.A Motors will review the details and contact you to confirm the appointment.</p><div className="bookingReceipt"><div><small>Service</small><b>{form.service}</b></div><div><small>Registration</small><b>{form.reg}</b></div><div><small>Preferred date</small><b>{form.date}</b></div></div><button className="bookingBtn" onClick={()=>{setSubmitted(false);setStep(0);setForm({service:'',reg:'',vehicle:'',date:'',name:'',phone:'',notes:''})}}>MAKE ANOTHER BOOKING</button></div></div></main>;
 return <main className="bookingPage"><div className="shell bookingShell"><header className="bookingHead"><span className="bookingKicker">ONLINE BOOKING</span><h1>Book workshop time.</h1><p>Five quick steps. Choose the job, tell us the car and pick a preferred date.</p></header><div className="bookingWorkspace"><aside className="bookingRail"><div className="bookingRailHead"><span>YOUR REQUEST</span><strong>{step+1} / 5</strong></div><div className="bookingRailSteps">{steps.map((s,i)=><div key={s} className={`bookingRailStep ${i===step?'active':''} ${i<step?'done':''}`}><i>{i<step?'✓':i+1}</i><span>{s}</span></div>)}</div><div className="bookingSelection"><small>SELECTED SERVICE</small><b>{form.service||'Not chosen yet'}</b>{selected&&<span>{selected.hint}</span>}{form.reg&&<><small>VEHICLE</small><b>{form.reg}</b></>}{form.date&&<><small>PREFERRED DATE</small><b>{form.date}</b></>}</div><div className="bookingRailHelp"><small>NEED HELP?</small><a href="tel:07484770941">Call 07484 770941</a></div></aside><section className="bookingStage"><div className="bookingStageTop"><span className="bookingStepTag">STEP {step+1} OF 5</span><span>{steps[step]}</span></div>
 {step===0&&<div className="bookingStepContent"><h2>What does your car need?</h2><p className="bookingIntro">Pick the closest option. If you are unsure, choose Diagnostics and describe the symptoms later.</p><div className="bookingChoices">{services.map(s=><button key={s.name} className="bookingChoice" onClick={()=>{update('service',s.name);setStep(1)}}><span className="bookingChoiceCode">{s.code}</span><span className="bookingChoiceText"><b>{s.name}</b><small>{s.hint}</small></span><span className="bookingChoiceArrow">→</span></button>)}</div></div>}
 {step===1&&<div className="bookingStepContent"><h2>Which vehicle is this for?</h2><p className="bookingIntro">Registration is required so Liam can identify the vehicle correctly.</p><div className="bookingFields"><label>REGISTRATION<input value={form.reg} onChange={e=>update('reg',e.target.value.toUpperCase())} placeholder="AB12 CDE" autoFocus/></label><label>MAKE / MODEL <span>(optional)</span><input value={form.vehicle} onChange={e=>update('vehicle',e.target.value)} placeholder="e.g. Ford Focus"/></label></div></div>}
 {step===2&&<div className="bookingStepContent"><h2>When would you like to come in?</h2><p className="bookingIntro">Choose your preferred date. This is a request until L.A Motors confirms the slot.</p><div className="bookingFields bookingFieldsStack"><label>PREFERRED DATE<input type="date" value={form.date} onChange={e=>update('date',e.target.value)}/></label><label>JOB DETAILS<textarea value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder="Describe the fault, service needed, warning light, noise or anything useful..."/></label></div></div>}
 {step===3&&<div className="bookingStepContent"><h2>How should we contact you?</h2><p className="bookingIntro">Liam will use these details to confirm the appointment or discuss the job.</p><div className="bookingFields"><label>NAME<input value={form.name} onChange={e=>update('name',e.target.value)} placeholder="Your name"/></label><label>MOBILE NUMBER<input value={form.phone} onChange={e=>update('phone',e.target.value)} inputMode="tel" placeholder="07..."/></label></div></div>}
 {step===4&&<div className="bookingStepContent"><h2>Check the request.</h2><p className="bookingIntro">Nothing is booked until L.A Motors confirms it with you.</p><div className="bookingSummary"><div><small>SERVICE</small><b>{form.service}</b></div><div><small>VEHICLE</small><b>{form.reg}</b><span>{form.vehicle||'Make/model not supplied'}</span></div><div><small>PREFERRED DATE</small><b>{form.date}</b></div><div><small>CONTACT</small><b>{form.name}</b><span>{form.phone}</span></div><div className="wide"><small>NOTES</small><span>{form.notes||'No additional notes'}</span></div></div>{error&&<div className="bookingError">{error}</div>}</div>}
 <div className="bookingActions">{step>0&&<button className="bookingBtn secondary" disabled={saving} onClick={()=>setStep(step-1)}>BACK</button>}{step>0&&step<4&&<button className="bookingBtn" disabled={!canContinue} onClick={()=>canContinue&&setStep(step+1)}>CONTINUE <span>→</span></button>}{step===4&&<button className="bookingBtn" disabled={saving} onClick={submit}>{saving?'SENDING...':'SEND BOOKING REQUEST'} <span>→</span></button>}</div></section></div></div></main>
}
