'use client';
import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import './booking.css';
const steps=['1 Service','2 Vehicle','3 Date','4 Contact','5 Review'];
const services=[['KEY','Car Keys'],['A/C','Air-Con'],['DIA','Diagnostics'],['SRV','Servicing & Repairs'],['MOT','MOT Interest'],['CAR','Vehicle Viewing']];
export default function Booking(){
 const params=useSearchParams();
 const [step,setStep]=useState(0);const [submitted,setSubmitted]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 const [form,setForm]=useState({service:'',reg:'',vehicle:'',date:'',name:'',phone:'',notes:''});
 useEffect(()=>{const requested=params.get('service');if(requested&&services.some(([,name])=>name===requested)){setForm(f=>({...f,service:requested}));setStep(1)}},[params]);
 const update=(k:string,v:string)=>setForm({...form,[k]:v});
 const canContinue=useMemo(()=>{if(step===1)return form.reg.trim().length>=5;if(step===2)return !!form.date;if(step===3)return form.name.trim().length>1&&form.phone.trim().length>6;return true},[step,form]);
 async function submit(){setSaving(true);setError('');try{const response=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({service:form.service,registration:form.reg,vehicle:form.vehicle,preferred_date:form.date,customer_name:form.name,phone:form.phone,notes:form.notes})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not save request.');setSubmitted(true)}catch(err){setError(err instanceof Error?err.message:'Could not save request.')}finally{setSaving(false)}}
 if(submitted)return <main className="bookingPage"><div className="shell"><div className="bookingCard bookingSuccess"><span className="bookingStepTag">REQUEST SENT</span><h1>Booking request received.</h1><p>L.A Motors can now review your request and contact you to confirm the appointment.</p><div className="bookingActions"><button className="bookingBtn" onClick={()=>{setSubmitted(false);setStep(0);setForm({service:'',reg:'',vehicle:'',date:'',name:'',phone:'',notes:''})}}>MAKE ANOTHER BOOKING</button></div></div></div></main>;
 return <main className="bookingPage"><div className="shell"><header className="bookingHead"><span>ONLINE BOOKING</span><h1>Book with L.A Motors</h1><p>Choose what you need, add the car and preferred date. Liam will confirm the appointment.</p></header><div className="bookingCard"><div className="bookingProgress">{steps.map((s,i)=><span key={s} className={i===step?'active':''}>{s}</span>)}</div>
 {step===0&&<section><span className="bookingStepTag">STEP 1 OF 5</span><h2>What does your car need?</h2><div className="bookingChoices">{services.map(([code,name])=><button key={name} className="bookingChoice" onClick={()=>{update('service',name);setStep(1)}}><span className="bookingChoiceCode">{code}</span><span><b>{name}</b><small>Tap to book</small></span></button>)}</div></section>}
 {step===1&&<section><span className="bookingStepTag">STEP 2 OF 5 · {form.service}</span><h2>Which vehicle?</h2><div className="bookingFields"><label>REGISTRATION<input value={form.reg} onChange={e=>update('reg',e.target.value.toUpperCase())} placeholder="AB12 CDE" autoFocus/></label><label>MAKE / MODEL <span style={{fontWeight:400,color:'#7f94a4'}}>(optional)</span><input value={form.vehicle} onChange={e=>update('vehicle',e.target.value)} placeholder="e.g. Ford Focus"/></label></div></section>}
 {step===2&&<section><span className="bookingStepTag">STEP 3 OF 5</span><h2>When suits you?</h2><div className="bookingFields"><label>PREFERRED DATE<input type="date" value={form.date} onChange={e=>update('date',e.target.value)}/></label><label>WHAT DO WE NEED TO KNOW?<textarea value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder="Describe the fault, service needed or anything useful for Liam..."/></label></div></section>}
 {step===3&&<section><span className="bookingStepTag">STEP 4 OF 5</span><h2>Your contact details</h2><div className="bookingFields"><label>NAME<input value={form.name} onChange={e=>update('name',e.target.value)} placeholder="Your name"/></label><label>MOBILE NUMBER<input value={form.phone} onChange={e=>update('phone',e.target.value)} inputMode="tel" placeholder="07..."/></label></div></section>}
 {step===4&&<section><span className="bookingStepTag">STEP 5 OF 5</span><h2>Check your request</h2><div className="bookingSummary"><div className="bookingSummaryRow"><b>Service</b><span>{form.service}</span></div><div className="bookingSummaryRow"><b>Vehicle</b><span>{form.vehicle||'Vehicle not supplied'} · {form.reg}</span></div><div className="bookingSummaryRow"><b>Preferred date</b><span>{form.date}</span></div><div className="bookingSummaryRow"><b>Contact</b><span>{form.name} · {form.phone}</span></div><div className="bookingSummaryRow"><b>Notes</b><span>{form.notes||'None'}</span></div></div>{error&&<div className="bookingError">{error}</div>}</section>}
 <div className="bookingActions">{step>0&&<button className="bookingBtn secondary" disabled={saving} onClick={()=>setStep(step-1)}>BACK</button>}{step>0&&step<4&&<button className="bookingBtn" disabled={!canContinue} onClick={()=>canContinue&&setStep(step+1)}>CONTINUE</button>}{step===4&&<button className="bookingBtn" disabled={saving} onClick={submit}>{saving?'SENDING...':'SEND BOOKING REQUEST'}</button>}</div></div></div></main>
}
