'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {getBrowserSupabase} from '../../../lib/supabase-browser';
import {DEMO_STOCK} from '../../../lib/demo-stock';

export default function DemoStockImporter(){
 const supabase=useMemo(()=>getBrowserSupabase(),[]);
 const[ready,setReady]=useState(false),[staff,setStaff]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{(async()=>{if(!supabase){setReady(true);return}const{data:s}=await supabase.auth.getSession();if(!s.session){setReady(true);return}const{data:isStaff}=await supabase.rpc('is_staff');setStaff(!!isStaff);setReady(true)})()},[supabase]);
 async function importDemo(){if(!supabase)return;setBusy(true);setMessage('');try{for(const car of DEMO_STOCK){const{data:existing}=await supabase.from('stock_vehicles').select('id').eq('slug',car.slug).maybeSingle();if(existing)continue;const payload={slug:car.slug,make:car.make,model:car.model,derivative:car.derivative,year:car.year,price:car.price,mileage:car.mileage,fuel:car.fuel,gearbox:car.gearbox,status:'available',featured:car.featured,image_urls:car.image_urls,description:'Demo showroom vehicle imported from the current advert information. Replace the demo image with the real vehicle photographs when available.'};const{error}=await supabase.from('stock_vehicles').insert(payload);if(error)throw error}setMessage('Demo cars are now in Stock Management. Liam can change each one to Available, Reserved, Sold or Draft and replace the demo photos.')}catch(e){setMessage(e instanceof Error?e.message:'Could not import demo stock.')}finally{setBusy(false)}}
 if(!ready)return <main className="dashLoading">Loading…</main>;
 if(!staff)return <main className="dashLogin"><div className="customerCard"><h1>Staff sign-in required</h1><p>This setup page is private.</p><Link className="customerPrimary" href="/dashboard">Staff Login</Link></div></main>;
 return <main className="shell section"><div className="dashboardTop"><div><div className="eyebrow">Vehicle Sales Setup</div><h1 className="sectionTitle">Demo Stock</h1><p className="muted">Import the current demo adverts into Liam's real stock manager so he can control them himself.</p></div><div className="actions"><Link className="btn ghost" href="/dashboard/stock">Stock Management</Link><Link className="btn ghost" href="/cars">Showroom</Link></div></div>{message&&<p className="formNotice">{message}</p>}<section className="panel"><h2>{DEMO_STOCK.length} demo adverts ready</h2><p className="muted">After importing, use Stock Management. Set a car to <b>Sold</b> or <b>Draft</b> and it disappears from the public showroom. Set it back to <b>Available</b> and it returns. Use Add Photos to replace the demo picture with the real car.</p><button className="btn" disabled={busy} onClick={importDemo}>{busy?'Importing…':'Import Demo Cars'}</button><div className="stockAdminList" style={{marginTop:20}}>{DEMO_STOCK.map(car=><article className="stockAdminRow" key={car.slug}><div><span className="statusPill status-available">demo</span><h3>{car.make} {car.model}</h3><p className="muted">{car.year||'Year on request'} · {car.mileage?`${car.mileage.toLocaleString()} miles`:'Mileage on request'} · £{car.price.toLocaleString()}</p></div></article>)}</div></section></main>
}
