import Link from 'next/link';

const services=[
 {code:'01',name:'Car Keys',price:'From £69',tag:'Most Popular',text:'Spare keys, lost keys, remote keys, cutting and immobiliser programming.',detail:'Blade keys from £69 · Remote keys from £99'},
 {code:'02',name:'Air Conditioning',price:'From £50',tag:'Stay Cool',text:'Air-conditioning re-gas enquiries with support for modern and older refrigerant systems.',detail:'R134a from £50 · R1234yf from £80'},
 {code:'03',name:'Diagnostics',price:'Quote',tag:'Fault Finding',text:'Warning lights, electrical issues and diagnostic checks to help identify the problem.',detail:'Clear advice before repair work'},
 {code:'04',name:'Servicing',price:'Quote',tag:'Maintenance',text:'Routine vehicle servicing and maintenance tailored to the car and its requirements.',detail:'Interim and full-service enquiries'},
 {code:'05',name:'Repairs',price:'Quote',tag:'Workshop',text:'Mechanical repairs with pricing based on the parts required and job complexity.',detail:'Brakes · suspension · batteries · general repairs'},
 {code:'06',name:'MOT',price:'Coming Soon',tag:'Register Interest',text:'MOT testing is planned. Customers can register now so L.A Motors can contact them when bookings open.',detail:'Future MOT reminders and booking'}
];

export default function Services(){return <main><section className="shell pageHero"><div className="eyebrow">L.A Motors Workshop</div><h1 className="sectionTitle">Straightforward service.<br/><span className="blueText">Proper local support.</span></h1><p className="muted lead">From a spare key to diagnostics and repairs, customers can understand the service, see guide pricing where available and move directly into booking.</p><div className="actions"><Link className="btn" href="/booking">Book Workshop</Link><a className="btn ghost" href="tel:07484770941">Call 07484 770941</a></div></section><section className="shell section compactTop"><div className="serviceList">{services.map((s)=><article className="serviceRow" key={s.name}><div className="serviceCode">{s.code}</div><div className="serviceMain"><div className="eyebrow">{s.tag}</div><h2>{s.name}</h2><p>{s.text}</p><small>{s.detail}</small></div><div className="serviceAction"><strong>{s.price}</strong><Link className="textLink" href="/booking">Book service →</Link></div></article>)}</div></section><section className="shell section"><div className="ctaBand"><div><div className="eyebrow">Not sure what to book?</div><h2>Tell Liam what the car is doing.</h2><p className="muted">Choose Diagnostics or Repairs and describe the issue. L.A Motors can then advise on the next step.</p></div><Link className="btn" href="/booking">Start Booking</Link></div></section></main>}
