import Link from 'next/link';

const services=[
 {icon:'🔑',name:'Car Keys',price:'From £69',accent:'Blade keys from £69 · Remote keys from £99',text:'Spare key, lost key or remote key? We can help with cutting and programming.',book:'Car Keys',cta:'Book Car Keys'},
 {icon:'❄',name:'Air-Con Re-Gas',price:'From £50',accent:'R134a from £50 · R1234yf from £80',text:'Air-con not blowing cold? Book a re-gas check for older and newer refrigerant systems.',book:'Air-Con',cta:'Book Air-Con'},
 {icon:'⚠',name:'Diagnostics',price:'Get a Quote',accent:'Warning lights · electrical faults · fault finding',text:'Got a warning light or an issue you cannot explain? Tell us what the car is doing and we will investigate.',book:'Diagnostics',cta:'Book Diagnostics'},
 {icon:'🛠',name:'Servicing',price:'Get a Quote',accent:'Routine maintenance · interim · full service',text:'Keep your car maintained with servicing matched to the vehicle and what it actually needs.',book:'Servicing & Repairs',cta:'Book a Service'},
 {icon:'🔧',name:'Repairs',price:'Get a Quote',accent:'Brakes · suspension · batteries · general repairs',text:'For mechanical repairs, send us the details and we will advise on the next step and likely costs.',book:'Servicing & Repairs',cta:'Book a Repair'},
 {icon:'MOT',name:'MOT',price:'Coming Soon',accent:'Register interest now',text:'MOT testing is planned. Leave your details now and we can contact you when bookings open.',book:'MOT Interest',cta:'Register for MOT'}
];

export default function Services(){return <main className="servicesPage">
<section className="servicesHero"><div className="shell servicesHeroInner"><div><span className="servicesKicker">L.A MOTORS · STROUD LTD</span><h1>What does your car need?</h1><p>Choose the service below and go straight into booking. If you are not sure, call us or book Diagnostics and describe the problem.</p><div className="servicesHeroActions"><Link href="/booking" className="servicesPrimary">BOOK A SERVICE</Link><a href="tel:07484770941" className="servicesSecondary">CALL 07484 770941</a></div></div><div className="servicesPromise"><strong>FAST ROUTE TO BOOKING</strong><span>1. Pick a service</span><span>2. Add your registration</span><span>3. Choose a preferred date</span><span>4. Liam confirms the booking</span></div></div></section>
<section className="shell servicesChooser"><div className="servicesSectionHead"><span>CHOOSE YOUR SERVICE</span><h2>Tap what you need</h2><p>No long forms first. Pick the job and we will take you straight to the booking.</p></div><div className="servicesGrid">{services.map(s=><article className="serviceChoice" key={s.name}><div className="serviceChoiceTop"><div className="serviceChoiceIcon">{s.icon}</div><div><h3>{s.name}</h3><strong>{s.price}</strong></div></div><p>{s.text}</p><small>{s.accent}</small><Link href={`/booking?service=${encodeURIComponent(s.book)}`} className="serviceBookBtn">{s.cta} <span>→</span></Link></article>)}</div></section>
<section className="shell servicesHelp"><div><span>NOT SURE WHAT TO CHOOSE?</span><h2>Tell Liam what the car is doing.</h2><p>Warning light, noise, starting problem or something just does not feel right? Book Diagnostics and explain it in the notes.</p></div><div className="servicesHelpActions"><Link href="/booking?service=Diagnostics" className="servicesPrimary">BOOK DIAGNOSTICS</Link><a href="tel:07484770941" className="servicesSecondary">CALL LIAM</a></div></section>
</main>}
