'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {getBrowserSupabase} from '../../../lib/supabase-browser';

type Job={id:string;customer_name:string;registration:string;vehicle:string;job_type:string;scheduled_date:string;status:string;description:string};
type Booking={id:string;customer_name:string;phone?:string;registration:string;vehicle:string;service:string;preferred_date:string;status:string;notes:string};
function dayKey(v?:string){if(!v)return 'Unscheduled';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'short'});}
function inputDate(v?:string){if(!v)return '';return v.slice(0,10)}

export default function SchedulePage(){
 const supabase=useMemo(()=>getBrowserSupabase(),[]);
 const[ready,setReady]=useState(false),[staff,setStaff]=useState(false),[jobs,setJobs]=useState<Job[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[working,setWorking]=useState('');
 useEffect(()=>{(async()=>{if(!supabase){setReady(true);return}const {data:s}=await supabase.auth.getSession();if(!s.session){setReady(true);return}const {data:isStaff}=await supabase.rpc('is_staff');if(!isStaff){setReady(true);return}setStaff(true);await load();setReady(true)})()},[supabase]);
 async function load(){if(!supabase)return;const[{data:j,error:je},{data:b,error:be}]=await Promise.all([supabase.from('job_cards').select('id,customer_name,registration,vehicle,job_type,scheduled_date,status,description').order('scheduled_date',{ascending:true}),supabase.from('bookings').select('id,customer_name,phone,registration,vehicle,service,preferred_date,status,notes').order('preferred_date',{ascending:true})]);if(je||be)setError((je||be)?.message||'Could not load schedule');setJobs((j||[]) as Job[]);setBookings((b||[]) as Booking[])}
 async function bookingStatus(id:string,status:string){if(!supabase)return;setWorking(id);setError('');const {error}=await supabase.from('bookings').update({status}).eq('id',id);setWorking('');if(error)return setError(error.message);setBookings(v=>v.map(x=>x.id===id?{...x,status}:x));setNotice(`Booking ${status}.`)}
 async function moveBooking(id:string,date:string){if(!supabase||!date)return;setWorking(id);const {error}=await supabase.from('bookings').update({preferred_date:date}).eq('id',id);setWorking('');if(error)return setError(error.message);setBookings(v=>v.map(x=>x.id===id?{...x,preferred_date:date}:x));setNotice('Booking date updated.')}
 async function jobStatus(id:string,status:string){if(!supabase)return;setWorking('j'+id);const {error}=await supabase.from('job_cards').update({status}).eq('id',id);setWorking('');if(error)return setError(error.message);setJobs(v=>v.map(x=>x.id===id?{...x,status}:x));setNotice(`Job ${status}.`)}
 if(!ready)return <main className="dashLoading">Loading schedule…</main>;
 if(!staff)return <main className="dashLogin"><div className="customerCard"><h1>Staff sign-in required</h1><p>This diary is private to L.A Motors staff.</p><Link className="customerPrimary" href="/dashboard">Staff Login</Link></div></main>;
 const activeBookings=bookings.filter(b=>b.status!=='cancelled'&&b.status!=='completed');
 const items=[...jobs.map(j=>({id:'j'+j.id,rawId:j.id,date:j.scheduled_date,title:j.job_type,customer:j.customer_name,reg:j.registration,vehicle:j.vehicle,status:j.status,kind:'Job' as const})),...activeBookings.map(b=>({id:'b'+b.id,rawId:b.id,date:b.preferred_date,title:b.service,customer:b.customer_name,reg:b.registration,vehicle:b.vehicle,status:b.status,kind:'Booking' as const}))].sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'));
 const groups=items.reduce((m,item)=>{const k=dayKey(item.date);(m[k]??=[]).push(item);return m},{} as Record<string,typeof items>);
 return <main className="schedulePage"><div className="scheduleShell"><header className="scheduleTop"><div><span className="premiumEyebrow">Workshop diary</span><h1>Bookings & Schedule</h1><p>Confirm, move and cancel bookings, and control live job progress from one screen.</p></div><div className="scheduleActions"><Link href="/dashboard" className="premiumBtn">← Dashboard</Link><Link href="/booking" className="premiumBtn primary">＋ Add Booking</Link></div></header>{error&&<p className="formError">{error}</p>}{notice&&<p className="formNotice">{notice}</p>}<section className="panel" style={{marginBottom:'24px'}}><div className="panelHead"><div><span className="premiumEyebrow">Booking control</span><h2>Customer requests</h2></div><span>{bookings.filter(b=>b.status==='pending').length} awaiting confirmation</span></div><div className="stockAdminList">{bookings.length===0?<p className="emptyState">No bookings yet.</p>:bookings.map(b=><article className="stockAdminRow" key={b.id}><div className="stockAdminDetails"><span className={`statusPill status-${b.status}`}>{b.status}</span><h3>{b.customer_name} · {b.registration||b.vehicle}</h3><p className="muted">{b.service}{b.phone?` · ${b.phone}`:''}</p>{b.notes&&<p>{b.notes}</p>}<label>Booked date <input type="date" defaultValue={inputDate(b.preferred_date)} onBlur={e=>{if(e.target.value&&e.target.value!==inputDate(b.preferred_date))moveBooking(b.id,e.target.value)}}/></label></div><div className="stockAdminActions"><button disabled={working===b.id} onClick={()=>bookingStatus(b.id,'confirmed')}>✓ Confirm</button><button disabled={working===b.id} onClick={()=>bookingStatus(b.id,'completed')}>Complete</button><button disabled={working===b.id} onClick={()=>bookingStatus(b.id,'cancelled')}>Cancel</button>{b.phone&&<a href={`tel:${b.phone}`}>Call</a>}</div></article>)}</div></section><div className="scheduleGrid">{Object.keys(groups).length===0?<section className="scheduleDay"><h2>No work scheduled</h2><p className="emptyState">New bookings and job cards will appear here.</p></section>:Object.entries(groups).map(([day,rows])=><section className="scheduleDay" key={day}><div className="scheduleDayHead"><h2>{day}</h2><span>{rows.length} {rows.length===1?'item':'items'}</span></div>{rows.map(r=><article className="scheduleItem" key={r.id}><div className="scheduleMarker"/><div><small>{r.kind}</small><h3>{r.title}</h3><p>{r.customer} · {r.reg||'No reg'}{r.vehicle?` · ${r.vehicle}`:''}</p></div><em className={`statusTag ${r.status}`}>{r.status.replace('_',' ')}</em>{r.kind==='Job'&&<div className="stockAdminActions"><button disabled={working===r.id} onClick={()=>jobStatus(r.rawId,'in_progress')}>Start</button><button disabled={working===r.id} onClick={()=>jobStatus(r.rawId,'completed')}>Complete</button></div>}</article>)}</section>)}</div></div></main>;
}
