'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {getBrowserSupabase} from '../../../lib/supabase-browser';

type Customer={id:string;name:string;phone:string|null;email:string|null;notes:string|null;created_at:string};
type Vehicle={id:string;customer_id:string|null;registration:string;make:string|null;model:string|null;year:number|null;mot_due:string|null;service_due:string|null};

export default function Customers(){
 const supabase=useMemo(()=>getBrowserSupabase(),[]);const [ready,setReady]=useState(false);const [signedIn,setSignedIn]=useState(false);const [customers,setCustomers]=useState<Customer[]>([]);const [vehicles,setVehicles]=useState<Vehicle[]>([]);const [query,setQuery]=useState('');const [message,setMessage]=useState('');const [form,setForm]=useState({name:'',phone:'',email:'',notes:'',registration:'',make:'',model:'',year:'',mot_due:'',service_due:''});
 useEffect(()=>{if(!supabase){setReady(true);return}supabase.auth.getSession().then(({data})=>{setSignedIn(!!data.session);setReady(true);if(data.session)load()});},[supabase]);
 async function load(){if(!supabase)return;const [c,v]=await Promise.all([supabase.from('customers').select('*').order('created_at',{ascending:false}),supabase.from('vehicles').select('*').order('created_at',{ascending:false})]);if(!c.error)setCustomers((c.data||[]) as Customer[]);if(!v.error)setVehicles((v.data||[]) as Vehicle[])}
 async function add(e:FormEvent){e.preventDefault();if(!supabase)return;setMessage('');const {data,error}=await supabase.from('customers').insert({name:form.name.trim(),phone:form.phone.trim()||null,email:form.email.trim()||null,notes:form.notes.trim()||''}).select('id').single();if(error){setMessage(error.message);return}if(form.registration.trim()){const {error:vError}=await supabase.from('vehicles').insert({customer_id:data.id,registration:form.registration.trim().toUpperCase(),make:form.make.trim()||null,model:form.model.trim()||null,year:form.year?Number(form.year):null,mot_due:form.mot_due||null,service_due:form.service_due||null});if(vError){setMessage(vError.message);return}}setForm({name:'',phone:'',email:'',notes:'',registration:'',make:'',model:'',year:'',mot_due:'',service_due:''});setMessage('Customer saved.');load()}
 const filtered=customers.filter(c=>`${c.name} ${c.phone||''} ${c.email||''}`.toLowerCase().includes(query.toLowerCase()));
 if(!ready)return <main className="shell section"><p className="muted">Loading…</p></main>;
 if(!supabase||!signedIn)return <main className="shell section"><div className="panel"><h1>Staff access required</h1><p className="muted">Open the Liam Dashboard and sign in first.</p><Link className="btn" href="/dashboard">Open Dashboard</Link></div></main>;
 return <main className="shell section"><div className="dashboardTop"><div><div className="eyebrow">Workshop CRM</div><h1 className="sectionTitle">Customers</h1><p className="muted">Keep customer contact details and vehicle records together.</p></div><div className="actions"><Link className="btn ghost" href="/dashboard">Dashboard</Link><Link className="btn ghost" href="/dashboard/jobs">Job Cards</Link></div></div>{message&&<p className="formNotice">{message}</p>}<div className="split"><form className="panel" onSubmit={add}><div className="eyebrow">Add Customer</div><h2>Customer & vehicle</h2><div className="formGrid"><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Registration<input value={form.registration} onChange={e=>setForm({...form,registration:e.target.value.toUpperCase()})}/></label><label>Make<input value={form.make} onChange={e=>setForm({...form,make:e.target.value})}/></label><label>Model<input value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></label><label>Year<input type="number" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/></label><label>MOT Due<input type="date" value={form.mot_due} onChange={e=>setForm({...form,mot_due:e.target.value})}/></label><label>Service Due<input type="date" value={form.service_due} onChange={e=>setForm({...form,service_due:e.target.value})}/></label><label className="full">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><button className="btn">Save Customer</button></form><section className="panel"><div className="eyebrow">Customer Database</div><h2>{customers.length} customers</h2><input placeholder="Search name, phone or email" value={query} onChange={e=>setQuery(e.target.value)}/><div className="customerList">{filtered.length===0?<p className="muted">No matching customers.</p>:filtered.map(c=>{const owned=vehicles.filter(v=>v.customer_id===c.id);return <article className="customerRow" key={c.id}><div><h3>{c.name}</h3><p className="muted">{c.phone||'No phone'}{c.email?` · ${c.email}`:''}</p>{c.notes&&<p>{c.notes}</p>}</div><div>{owned.map(v=><div className="vehicleMini" key={v.id}><b>{v.registration}</b><span>{[v.make,v.model,v.year].filter(Boolean).join(' ')||'Vehicle details not set'}</span><small>MOT: {v.mot_due||'—'} · Service: {v.service_due||'—'}</small></div>)}</div></article>})}</div></section></div></main>
}
